# Generated by Django 5.0.4 on 2024-05-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='prerequisites',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='skills_you_learn',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='who_should_enroll',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
